### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MMarvasti** [AlfonsoLRz/RGBThermalFusion#1]
Hello,

Please guide me on how to run your code (there are no .sln in the files). Besides, please provide the raw data, reference point clouds, etc to verify your code.

Thank you in advance.
Best,
Mojtaba

**Comment by AlfonsoLRz** [comment]
Hi Motjaba!,

We only provided the source code for the manuscript implementation, as it is integrated with a larger OpenGL-based application that belongs to the research group. Therefore, it is not intended to be a desktop application. The main files concerning thermal image projection into the RGB point cloud are found in EnvImage, OpenCVImage and NaiveThermalAugmentation (for a basic behaviour). In addition, Environment handles most of the program workflow; from reading input calibration files (generated with Pix4D) to the final thermal projection. Besides rendering, OpenGL is only applied for enhancements of the basic projection. Thus, C++ along with OpenCV are more than enough for the basic approach.

Sincerely yours,
Alfonso.

**Comment by MMarvasti** [comment]
Thanks, Alfonso.
Have the input images (e.g., RGB & thermal images used in the manuscript) been released publicly?

**Comment by AlfonsoLRz** [comment]
Hi Motjaba!,
We have not released the dataset publicly. However, if you plan to use it to test our algorithm, I guess I could share it partially with you, including the point cloud (some partners are still working on further applications over the represented study area, so I'd prefer not to release it completely).

**Comment by MMarvasti** [comment]
Hi Alfonso,
I would appreciate it if you could share the requirements for testing your algorithm (including images, etc.).
Also, if it's possible, would you please share the main source file that uses the algorithm files and shows the output?
My email address is mojtaba.marvasti@ualberta.ca .
Thank you in advance.
Mojtaba
